services:
  - type: cron
    name: crypto-hourly-job
    runtime: docker
    region: frankfurt
    schedule: "0 * * * *"
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: SUPABASE_URL
        value: https://wzavsqebxbkzjztsruzr.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: USE_TESTNET
        value: "true"
