name: Pipeline de Coleta de Dados Crypto

on:
  schedule:

    - cron: '0 * * * *'
    
    - cron: '5 0 * * *'

  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Escolha qual rotina rodar manualmente'
        required: true
        default: 'hourly'
        type: choice
        options:
          - hourly
          - daily

jobs:

  # JOB 1: Hourly

  hourly-collection:
    name: Coleta Horária (Tickers + Klines 1h)
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.job_to_run == 'hourly' || github.event_name == 'schedule' && github.event.schedule == '0 * * * *'
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar uv e Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          working-directory: back-end

      - name: Executar Coleta Horária
        working-directory: back-end
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        run: |
          uv run python jobs.py hourly

  # JOB 2: Daily

  daily-collection:
    name: Coleta Diária (Klines 1d)
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.job_to_run == 'daily' || github.event_name == 'schedule' && github.event.schedule == '5 0 * * *'
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar uv e Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          working-directory: back-end

      - name: Executar Coleta Diária
        working-directory: back-end
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        run: |
          uv run python jobs.py daily